package com.bhagya.research.entity.enums;

public enum EventCategory {
	POLITICAL_AND_PROTEST, RELIGIOUS_AND_CULTURAL, ENTERTAINING_AND_PERFORMING_ARTS, SPORTS, EDUCATIONAL,
	FOOD_AND_DRINKS, HEALTH_AND_WELLBEING, OTHER
}
